### PR TITLE
Class handlers new

### PR DESCRIPTION
**Pull request by seanhess**
I managed to finally figure out how to resolve handlers via a typeclass. This is an alternative to #41, and in response to #31. 

Unfortunately we couldn't fit it into the `HyperView` class, because this class needs to carry the `es :: [Effect]` type variable. Multiple functions require that `HyperView` work outside of effect handlers, like `button :: HyperView id => Action id -> Mod -> View id ()`

Here's what they look like in this branch:

```
{-# LANGUAGE UndecidableInstances #-}

page :: (Hyperbole :> es, Concurrent :> es, Reader (TVar Int) :> es) => Page es '[Counter]
page = load $ do
  var <- ask
  n <- readTVarIO var
  ...

instance HyperView Counter where
  type Action Counter = Count

instance (Reader (TVar Int) :> es, Concurrent :> es) => Handle Counter es where
  handle _ Increment = do
    n <- modify $ \n -> n + 1
    pure $ viewCount n
```

They also require UndecidableInstances. But other than those two downsides, the advantages of being able to look up a handler by hyperview are great. That page function is much simpler.

### CODE REVIEW

**Comment by seanhess** [comment]
@benjaminweb can I get your feedback on this approach vs #41? Which do you think is better?

**Comment by benjaminweb** [comment]
Will do once I’ve tried out type class and tuple approach (days)!

**Comment by seanhess** [comment]
One other downside to this approach: it makes passing arguments to handlers more complicated. It's not that big of a deal to add a `Reader whatever :> es` constraint and runReader in the main app, but ghc is resisting my attempts to make it casual to add context when defining the page:

Before:

```
page :: (Hyperbole :> es, Concurrent :> es) => TVar Int ->  Page es '[Counter]
page var = handle (counter var) $ do
  n <- readTVarIO var
  ...
```

Now:

```
-- you MUST call runReader from outside of this function
-- if you attempt to runReader inside it, the types don't line up (because the es for the page has to match)
page :: (Hyperbole :> es, Concurrent :> es, Reader (TVar Int) :> es) =>  Page es '[Counter]
page = do
  -- can't do this here: runReader var $ do
  n <- readTVarIO var
  ...
```

This isn't a problem for something like Counter, because the top-level app controls that TVar anyway, but it is a problem in my real application at work, where I've created a reusable hyperview with a cancel button that can does different things on two pages. The handler for It looks like this (using the syntax of #41)

```
inversions :: (Hyperbole :> es, ...) => Eff es (View InversionStatus ()) -> InversionStatus -> InversionAction -> Eff es (View InversionStatus ())
inversions onCancel (InversionStatus ip iip ii) = \case
  Cancel -> do
    send $ Inversions.Remove ii
    onCancel
  Download -> do
    ...
```

It is used on two different pages with a different `onCancel`. 

```
page1
  :: (Hyperbole :> es, ...)
  => Id Proposal
  -> Id Inversion
  -> Eff es (Page (InversionStatus : Require InversionStatus))
page1 ip i = handle (inversions redirectHome, ...) $ do

page
  :: (Hyperbole :> es, ...)
  => Id Proposal
  -> Id InstrumentProgram
  -> Eff es (Page (ProgramInversions : ProgramDatasets : InversionStatus : InversionViews))
page ip iip = do
  handle (inversions (deleteInversion ip iip), ...) $ do
```

Maybe reusing a hyperview like this is a bad idea. In which case this being a PITA is a good thing?

**Comment by benjaminweb** [comment]
Incorporated both variants into my playground:
#41: https://github.com/benjaminweb/hyperbole-tutorial/blob/tuple-list-handlers/app/Main.hs
#43:https://github.com/benjaminweb/hyperbole-tutorial/blob/typeclass-list-handlers/app/Main.hs

I instantly like #43 more.
It is appealing to simplify the interfacing (and/through documented examples) further. That's my intuition right now. — What's your's?

Observations:
- #43 makes it to me much clearer what the purpose of the `handle` function is, point for #43
- #41 requires less changes to existing code

**Comment by benjaminweb** [comment]
Regarding Passing context to handlers.
In my (limited) experience I've passed to handlers mostly the same arguments (contexts).
I wished there was / I knew a better way to pass it around.

I haven't encountered the situation of parametrized handlers for reusing hyperviews yet.

Naive question: What you've done for #43, namely engineering the variants of handlers (handled by load?) on the type class level, could you do similar for the arguments of handlers? Though, it might be overkill or not viable at all, just sharing this notion with you.

**Comment by seanhess** [comment]
Thanks, that’s very helpful. I had been leaning towards #41 because it is more explicit, but I think you are right. A lot of the design comes from Elm, but that throws off my intuition sometimes because Elm doesn’t have type classes. I think you’re right that #43 will feel more intuitive to Haskell programmers. 

> https://github.com/seanhess/hyperbole/pull/43 makes it to me much clearer what the purpose of the handle function is

> Naive question: What you've done for https://github.com/seanhess/hyperbole/pull/43, namely engineering the variants of handlers (handled by load?) on the type class level, could you do similar for the arguments of handlers? Though, it might be overkill or not viable at all, just sharing this notion with you.

These comments taken together are interesting. We pass the View Action into the handler so the user can pattern match on it. It’s the simplest way to make sure they handle all possible actions. 

But the View Id is only useful for context: database ids for example (see Example.Contacts). The view Id could certainly be moved into a `Reader id :> es` constraint. That would be much cleaner in the common use case where a handler doesn’t need the view id for anything. 

We could theoretically do something similar for the action, but can you imagine a different way to specify what an action does?

**Comment by seanhess** [comment]
I just pushed a new update to this branch that incorporates your idea of hiding the view id behind a reader context. I like it! 

Here's what it looks like if you don't need the view id: Example.Counter

```
instance HyperView Counter where
  type Action Counter = Count
instance (Reader (TVar Int) :> es, Concurrent :> es) => Handle Counter es where
  handle Increment = do
    n <- modify (+ 1)
    pure $ viewCount n
  handle Decrement = do
    n <- modify (subtract 1)
    pure $ viewCount n
```

If you DO need the view id, there's a new funciton `viewId :: Reader id :> es => Eff es id`

```
instance HyperView Contact where
  type Action Contact = ContactAction
instance (Users :> es, Debug :> es) => Handle Contact es where
  handle action = do
    -- No matter which action we are performing, let's look up the user to make sure it exists
    Contact uid <- viewId
    u <- Users.find uid
    case action of
      View -> do
        pure $ contactView u
      Edit -> do
        pure $ contactEdit u
      Save -> do
        delay 1000
        unew <- parseUser uid
        Users.save unew
        pure $ contactView unew
```

To put it through its paces, and to make sure that we have alternatives to argument-passing for reuse, I updated the advanced Contacts example to demonstrate reusing a HyperView on different pages. 

The new Example.Contact lets a user edit a contact from a separate page:

```
-- Example adding a reader context to the page, based on an argument from the AppRoute
response :: (Hyperbole :> es, Users :> es, Debug :> es) => UserId -> Eff es Response
response uid = runReader uid $ runPage page


-- The page assumes all effects have been added
page
  :: forall es
   . (Hyperbole :> es, Users :> es, Debug :> es, Reader UserId :> es)
  => Page es '[Contact]
page = do
  uid <- ask
  u <- Users.find uid
  pure $ do
    col (pad 10 . gap 10) $ do
      hyper (Contact uid) $ contactView u

```

Example.Contacts uses the `Contact` view from Example.Contacts, modifying what the edit button does to add a delete button

```
-- Reuse Contact View ----------------------------------

-- Make a newtype so we can customize the behavior of the handler
newtype InlineContact = InlineContact Contact
  deriving newtype (ViewId)


instance HyperView InlineContact where
  type Action InlineContact = ContactAction
instance (Users :> es, Debug :> es) => Handle InlineContact es where
  handle Edit = do
    -- Edit will show the normal view, plus a delete button
    InlineContact (Contact uid) <- viewId
    u <- Users.find uid
    pure $ inlineEdit u
  handle other = do
    -- all the other views are handled by `Handle Contact es`
    InlineContact c <- viewId
    asdf <- runReader c $ handle @Contact other
    pure $ addContext c asdf

inlineEdit :: User -> View InlineContact ()
inlineEdit u = onRequest contactLoading $ col (gap 10) $ do
  InlineContact c <- context
  addContext c $ contactEdit' u
  target Contacts $ button (DeleteUser u.id) (Style.btn' Danger . pad (XY 10 0)) (text "Delete")

```

**Comment by benjaminweb** [comment]
That's pretty straightforward: https://github.com/benjaminweb/hyperbole-tutorial/commit/ac46e4823ca30063073c09ed5ecd87429c70a836
It's simpler because we don't use `load` any more.

…looking at: https://github.com/seanhess/hyperbole/blob/6f36420cd8770a316fa9546589131892de44caae/example/HelloWorld.hs
Would it be simpler to define a View via a type instance?

**Comment by seanhess** [comment]
> …looking at: https://github.com/seanhess/hyperbole/blob/6f36420cd8770a316fa9546589131892de44caae/example/HelloWorld.hs Would it be simpler to define a View via a type instance?

If you mean adding a view function to the Handler or HyperView class, no I don't think that would help. Views need data to render, like a type from the database or something. Right now, you can gather anything you need in a handler and pass it directly to the view. To add a view function to one of the typeclasses we would also have to add some "model" datatype, which would complicate it more than I'm comfortable with.

**Comment by seanhess** [comment]
I just switched my work project over to this branch and it's working great. Let's pull the trigger. Thanks for the feedback @benjaminweb!

**Pull request merged**
