### PR TITLE
Added reqParamMaybe function

### PR DESCRIPTION
**Pull request by tusharad**
Hi @seanhess ,

This PR introduces a new function, `reqParamMaybe`, which is a Maybe version of the existing reqParam function. It is designed to provide flexibility by returning a Maybe type, enabling better handling of optional parameters in requests.

Please let me know if there are any changes or additional requirements needed.

Thanks!

### CODE REVIEW

**Comment by seanhess** [comment]
Hmm, you're right that there's a hole here. We need to improve how all these functions work together. I like how the word "lookup" implies a `Maybe`.  Can we rename your function to have "lookup" int the name instead of "Maybe"?

It also looks like the type of the Query Parameter is inconsistent. We currently have:

```
reqParams :: (Hyperbole :> es) => Eff es Query
reqParam :: forall a es. (Hyperbole :> es, FromHttpApiData a) => Text -> Eff es a
lookupParam :: BS.ByteString -> Query -> Maybe Text
```

Let's refactor to make them all either `Text` or `ByteString`.  

Also, `lookupParam` feels fairly useless right now, since it doesn't run `parseQueryParam`. 


```
-- This could be Text, as long as it is consistent
type QueryParam = BS.ByteString

reqParams :: (Hyperbole :> es) => Eff es Query
reqParam :: (Hyperbole :> es, FromHttpApiData a) => QueryParam -> Eff es a

-- This is your function. What should it be named?
lookupParam :: (Hyperbole :> es, FromHttpApiData a) => QueryParam -> Eff es (Maybe a)

-- Do we want to get rid of this? Is there a good way to create a `parseParam` function instead that can be used by either of the above?
lookupParam :: QueryParam -> Query -> Maybe Text
```

Do you mind thinking about this and revising the PR? We can sneak it into the 0.4 release if it's done soon.

**Comment by tusharad** [comment]
Hi @seanhess 

```haskell
type QueryParam = Text

-- | Return the entire list of 'QueryParam's
reqParams :: (Hyperbole :> es) => Eff es [(QueryParam, Text)]

-- | For a given 'QueryParam', return the value else throw an error
reqParam :: (Hyperbole :> es) => QueryParam -> Eff es Text

-- | For a given 'QueryParam', return the value else 'Nothing'
lookupParam :: (Hyperbole :> es) => QueryParam -> Eff es (Maybe Text)

-- | Whether the param is present or not
hasParam :: QueryParam -> Query -> Bool
```

What do you think of above names and types. Please do let me know any changes are required. I can go forward with that and push the commit.

**Comment by seanhess** [comment]
I like the direciton. You might struggle converting the params to `[(Text, Text)]` preemptively. They start as `[ByteString, Maybe ByteString]`, reflecting that a parameter value can be empty (flags). 

Also, we definitely need functions that parse them for us. Like how `reqParam` automatically resolves `FromHttpApiData`. In your proposal how would that happen?

**Comment by tusharad** [comment]
Instead of [(Text, Text)], we can use [(Text, Maybe Text)]. This aligns directly with how parameters are structured, accounting for cases where a parameter value may be empty (such as flags). Using the [queryToQueryText](https://hackage.haskell.org/package/http-types-0.12.4/docs/Network-HTTP-Types-URI.html#v:queryToQueryText) function , we can transform [ByteString, Maybe ByteString] into [(Text, Maybe Text)] efficiently. This also avoids the need for manual encodeUtf8 and decodeUtf8 calls, as queryToQueryText handles the conversion to Text for us. With this change, the reqParam function can continue to operate as it currently does

**Comment by seanhess** [comment]
👍 I like it. 

Still need to figure out parameter parsing. It might be worth thinking about this issue along the way: https://github.com/seanhess/hyperbole/issues/32

**Comment by tusharad** [comment]
Replaced [ByteString, Maybe ByteString] query representation with QueryText ([(Text, Maybe Text)]), using queryToQueryText for conversion. This simplifies handling of query parameters, ensuring consistent and native Text processing.

Functions like reqParams and lookupParam now directly operate on QueryText, eliminating the need for manual encodeUtf8 and decodeUtf8.

Let me know if further refinements are needed! Thanks!

**Comment by seanhess** [comment]
Looks great! I might think harder and tweak naming later but nice work!

**Pull request merged**
